###########################################
# FakeTrollPlus plugin v3.4.0 by Lori00. #
###########################################


# Keeping the Updater enabled is recommended. Only disable if the server is not connected to the internet.
check-updates: true

# These settings enable/disable admin-protection. Set to true to protect admins.
# Admins are the ones who have the permission 'faketroll.exempt'.
# Operators are granted the permission by default.
exempt-admins: false
no-admin-trolling: '&cYou may not troll this player!'
console-bypass: true

# Set whether the permission 'faketroll.help' is required to see the help menu.
help:
  require-permission: true

enable-fake-op: true
enable-fake-deop: true

enable-fake-alert: true
fake-broadcast:
  enable: true
  format: '&6[&4Broadcast&6]&a '

fake-join:
  enable: true
  message: '&e%Player% joined the game'
fake-leave:
  enable: true
  message: '&e%Player% left the game'
  
enable-hurt: true
enable-poison: true
enable-murder: true
enable-burn: true

inventory-lock:
  enable: true
  do-target-msg: true
  target-msg: '&3Sorry, but you are not allowed to access your inventory at the moment.'

freeze:
  enable: true
  freeze-msg: '&3You have been frozen! Please do not log off!'
  unfreeze-msg: '&3You have been unfrozen and are free to log off!'
  do-move-attempt-msg: true
  move-attempt-msg: '&3You are not allowed to move!'

enable-gibberish: true

rename-items:
  enable: true
  do-target-msg: false
  target-msg: '&cOops! It seems that there is something wrong with your items!'

tprandom:
  enable: true
  tp-bounds: 10000
  do-msg-to-target: false
  msg-to-target: '&6It seems that you have been teleported!'
  
enable-portal: true

enable-spam: true
fake-msg:
  enable: true
  format: '&6[&r{PLAYER} &6-> &cme&6]&f {MESSAGE}'
  allow-fake-names: true
  
fake-chat:
  enable: true
  allow-unexisting-nicks: true
  format: '<{PLAYER}> {MESSAGE}'

enable-clearinv: true
random-inv:
  enable: true
  do-target-msg: false
  target-msg: '&3Something unexpected happened.'
  
fake-pay:
  enable: true
  format: '&a${AMOUNT} has been received from {SENDER}&f.'

enable-fake-crash: true

fake-ban:
  enable: true
  ban-message: 'You are banned from this server! Reason: {REASON}'
  do-broadcast: true
  broadcast-msg: '&cPlayer {PLAYER} has been banned by {STAFF} for {REASON}!'

enable-fake-god: true

fake-afk:
  enable: true
  format-on: '&7* {PLAYER} &7is now AFK.'
  format-off: '&7* {PLAYER} &7is no longer AFK.'

enable-anvil: true

explode:
  enable: true
  power: 4
  set-fire: true
  
explode-blocks:
  enable: true
  power: 0.5
  set-fire: false

enable-force-cmd: true

enable-launch: true

swap:
  enable: true
  invalid-target: '&6Sorry, but at least one of your targets was not found.'
  send-message-to-target: true
  target-msg: '&bSomething unexpected happened...'

bury:
  enable: true
  depth: 6.0
  do-msg-to-target: true
  msg-to-target: '&bUh, oh: It appears that you have been buried alive!'
  
no-pickup:
  enable: true
  alert-victim: true
  on-enable: '&3You may no longer pick up items from the ground!'
  on-disable: '&3You may now pick up items from the ground!'
  
badfood:
  enable: true
  duration: 10
  
enable-replaceinv: true
enable-push: true
enable-cobweb: true

# Blacklist configurations
enable-blacklist: true
blacklist: '&4You were blacklisted from the network!'
already-blacklisted: '&4Player already blacklisted!'
not-blacklisted: '&4Player not blacklisted!'
on-blacklist: '&6You have blacklisted &c%player%'
on-unblacklist: '&6You have unblacklisted &c%player%'

# Logging options: - After editing this setting, you will need to restart the server for the changes to take place.
enable-logs: true

# Should disabled commands display the vanilla unknown command message when executed?
# If not, change the message below:
message-for-disabled-cmds: '&fUnknown command. Type "/help" for help.'

# Set the message displayed when the target's name is either invalid or they are not online.
invalid-target: '&6Player not found.'
